---

    - name: change SELinux is disable
      selinux:
        state: disabled

    - name: stop firewall
      shell: systemctl stop firewalld

    - name: stop auto start a firewall
      shell: systemctl disable firewalld

    - name: install oracle-database-preinstall   rpm
      yum:
        name: "{{soft_dir}}/oracle-database-preinstall-19c-1.0-1.el7.x86_64.rpm"
        state: present
      with_items:
        - oracle-database-preinstall-19c-1.0-1.el7.x86_64.rpm

    - name: stop auto start a avahi-daemon
      shell: systemctl disable avahi-daemon
      ignore_errors: True

    - name: stop avahi-daemon
      shell: systemctl stop avahi-daemon
      ignore_errors: True

    - name: stop auto start a chronyd
      shell: systemctl disable chronyd
      ignore_errors: True

    - name: stop chronyd
      shell: systemctl stop chronyd
      ignore_errors: True
